services:
  esggulcode:
    build: ./php
    image: esggulcode_php:latest
    container_name: esggulcode
    hostname: "esggulcode"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - esggulcode_db
  esggulcode_db:
    image: mariadb:10.2
    container_name: esggulcode_db
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx_esggulcode:
    build: ./nginx
    image: nginx_esggulcode:latest
    container_name: nginx_esggulcode
    hostname: "nginx_esggulcode"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - esggulcode